### ISSUE TITLE
Ionic2 slider not working with latest version of wkwebvje

### ISSUE THREAD

**Issue by absolutsoul** [ionic-team/cordova-plugin-wkwebview-engine#121]
Slider unresponsive when updating to latest version

**Comment by kabus202** [comment]
I dont have problems with the slider here.

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.0
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.9.4
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13

**Comment by manucorporat** [comment]
This plugin just uses the WKWebView API provided by Apple, we dont actually implement anything, if this is a bug it is in the framework or in your own code.
