### ISSUE TITLE
Input fields: bugs on iOS emulator

### ISSUE THREAD

**Issue by dspachos** [ionic-team/cordova-plugin-wkwebview-engine#135]
I'm using the latest version of WKWEBVIEW, latest Ionic libs etc.
When I'm on iOS emulator every input field (including searchbar component) it is not working as expected: keyboard does not fire up, cursor inside input field is invisible, every attached event isn't working. 

When I'm on the real device, everything works fine, though. 

Although I can live with that bug, it's a little bit annoying, slows down the development. Any solutions or suggestions why is this happening?

**Comment by dspachos** [comment]
No answer until today, I close the issue

**Comment by HartHerbert** [comment]
well I had this problem too, just turn off the softwarekeyboard of the emulator and it will work. the appstore didn't accept my app for the appstore because of this. its just this softwarekeyboard

**Comment by dspachos** [comment]
This is the list of my plugins. Are you saying that I have to remove the keyboard plugin or the App Store will reject my app?

```
> cordova plugin ls
✔ Running command - done!
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4-dev "Cordova WKWebView Engine"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Comment by manucorporat** [comment]
could you guys try ionic's nightly? 

```
npm install ionic-angular@nightly
```

**Comment by HartHerbert** [comment]
@dspachos you dont have to uninstall any plugin. 
turn off your Sofwarekeyboard of your emulator. Go to the emulator under Hardware>Keyboard>Toggle Software Keyboard or just type CMD+K, thats the shortcut. Toggling the software keyboard will allow you to click on input fields. It works on every device, just the emulator cant click on inputs using this sofware keyboard

**Comment by dspachos** [comment]
Thanks for the comment. But you wrote "the appstore didn't accept my app for the appstore because of this". What is "this"? 
I'll submit my app and I want to avoid rejects..

**Comment by HartHerbert** [comment]
the appstore was checking my app and tzen they refused it because they couldn't click on the input fields. then in the resolution center (In Itunesconnect) i told them its because of this software keyboard and after that they said my app was good and accepted it.

**Comment by dspachos** [comment]
I understand now!..Thanks for letting me know.
