### ISSUE TITLE
CORS not working

### ISSUE THREAD

**Issue by do-web** [ionic-team/cordova-plugin-wkwebview-engine#143]
On some request i get the error "Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin." but some others are working. I have added config params to the config.xml.

**Comment by codebeauty** [comment]
@do-web can you provide more details. I have the same issue in my case. I saw all the other threads but there was not a real solution.

Issue on:
- iOS
- latest Ionic & Cordova
- https requests

**Comment by do-web** [comment]
I just reinstall the plugin, then it works.
