### ISSUE TITLE
Installing this Plugin when Crosswalk is already installed

### ISSUE THREAD

**Issue by Mr-Anonymous** [ionic-team/cordova-plugin-wkwebview-engine#148]
I have already installed `cordova-plugin-crosswalk-webview` plugin in my ionic app and this plugin also includes for iOS platform. However, I wish to use your `cordova-plugin-wkwebview-engine` plugin for my iOS App and continue to use `cordova-plugin-crosswalk-webview` plugin in my Android App. If I install `cordova-plugin-wkwebview-engine` without removing `cordova-plugin-crosswalk-webview`, will that cause any conflict? When I looked through a few posts here, I noticed some of the config.xml files shows both of these plugins and it appears some users have both installed. So, I am curious, shouldn't having both plugins installed cause conflicts with the iOS app since adding iOS platform also installs the crosswalk's iOS plugin automatically?

**Comment by dylanvdmerwe** [comment]
Crosswalk and Wkwebview can be used together. I've done this numerous times. Crosswalk purely does things for Android, whereas this plugin is for iOS.

**Comment by manucorporat** [comment]
exactly! you can and should use both!! do not worry about it!

**Comment by Mr-Anonymous** [comment]
Thank you @dylanvdmerwe and @manucorporat 

Since Cordova crosswalk includes iOS support automatically now, I was concerned. After your reply, I installed WKwebview for my iOS and it works well. I had initial hiccups related to CORS but once I enabled localhost origin in my server, all is working now.

Thank you for your response. It helped heaps and I appreciate that.
