### ISSUE TITLE
Page not Scrollable

### ISSUE THREAD

**Issue by Mr-Anonymous** [ionic-team/cordova-plugin-wkwebview-engine#149]
I have successfully installed this wkwebview engine for my ionic iOS App and have also set up the CORS from my server side. The problem I have now is, I am unable to scroll the App page. The page appears fixed. In the mobile phone the page does not scroll down when trying to go down on the screen. However in the Simulator I am able to move down using the arrow keys in my Mac but I cannot scroll in the App when I move by click & scroll on the Simulator screen.

Has anyone experience this issue? I have the same App on Cordova Crosswalk for Android and the page is scrollable on Android. The Web App version also works fine from all browsers so its not the css issue. Also, when I uninstall this wkwebview engine, the page is scrollable again in the default iOS Webview. However, as soon as I install this wkwebview plugin, the page is not scrolling vertically. Everything else works though, such as the buttons and links in the visible area.

Can someone guide me here please? Do I need to add any additional setting for this? This behaviour seems very weird.

**Comment by Mr-Anonymous** [comment]
An update on this: I uninstalled this ionic-team/cordova-plugin-wkwebview-engine plugin and then installed apache/cordova-plugin-wkwebview-engine ( https://github.com/apache/cordova-plugin-wkwebview-engine ) with the same settings and it works fine there. The page is scrollable, etc with the cordova plugin version. But only when I have this particular plugin (ionic-team/cordova-plugin-wkwebview-engine) installed, I am having this issue where the page is not scrollable.

-- Neel.

**Comment by morganabel** [comment]
I had the same problem with the newest master. I was able to work around by using this version (commit 5a67fd57e06c8a44f43a332a379d5e13ef2a7d1a): https://github.com/ionic-team/cordova-plugin-wkwebview-engine/tree/5a67fd57e06c8a44f43a332a379d5e13ef2a7d1a

**Comment by Mr-Anonymous** [comment]
Thank you @morganabel 

I wonder if someone can identify what is causing this issue with the newest master? If yes, can we get an ETA on when the update could be added to the master?

In the mean time, I will try and install the version in that commit. Thanks for your support.

**Comment by Mr-Anonymous** [comment]
Sorry @morganabel , a question, how can I install the plugin from that particular tree instead of the master? Cuz right now `ionic cordova plugin add https://github.com/driftyco/cordova-plugin-wkwebview-engine.git --save` installs the master version, but how can I choose that suggested version for installation in my ionic app?

**Comment by morganabel** [comment]
The way I did it:

- opening that tree in github
- downloading project as a zip
- extract and install from local folder

 I use visual studio to do it so I don't know the exact cli line but I think you can just replace the url with a local disk folder location

**Comment by Mr-Anonymous** [comment]
makes sense. I will give that a go. Thanks for that. 

At the moment, I have installed the master copy of Apache Cordova's WkWebView plugin ( https://github.com/apache/cordova-plugin-wkwebview-engine ) and that seems to work fine without this scrolling issue so I am in a dilemma whether I should change to your suggested version of this plugin or leave it as it is as the Cordova's original plugin since I have to publish my app by this weekend.

**Comment by manucorporat** [comment]
@Mr-Anonymous are you using ionic? or another solution for web apps?

**Comment by Mr-Anonymous** [comment]
I am using ionic framework. I am basically converting a web app that was build on Angular 1.5 and now I have created the mobile app for that by wrapping it with ionic framework v1.

**Comment by manucorporat** [comment]
For the record: 
https://github.com/ionic-team/cordova-plugin-wkwebview-engine/blob/master/src/ios/CDVWKWebViewEngine.m#L256

**Comment by Mr-Anonymous** [comment]
cool... that makes sense. I will try that preference setting in my config file right now and will post back in 5-10mins. Thank you @manucorporat

**Comment by Mr-Anonymous** [comment]
Hi @manucorporat I uninstalled the plugin and redid again with a clean install, downloaded the latest version of this plugin and also added the `ScrollEnabled` setting to `true` but unfortunately the scrolling still doesn't work. Its the same as before where the page is unscrollable.
```
    <allow-navigation href="http://localhost:8080/*" />
    <allow-navigation href="https://www.example.com/*" />
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
    <preference name="ScrollEnabled" value="true" />
```

**Comment by Mr-Anonymous** [comment]
```
[settings cordovaFloatSettingForKey:@"ScrollEnabled" defaultValue:NO]
```
Should that be `cordovaBoolSettingForKey`? Would that make a difference?

**Comment by Mr-Anonymous** [comment]
Hi @manucorporat 

The following fixes the issue: 
In `src/ios/CDVWKWebViewEngine.m`, Change:
```
wkWebView.scrollView.scrollEnabled = [settings cordovaFloatSettingForKey:@"ScrollEnabled" defaultValue:NO];
```
To:
```
wkWebView.scrollView.scrollEnabled = [settings cordovaBoolSettingForKey:@"ScrollEnabled" defaultValue:NO];
```
After changing `cordovaFloatSettingForKey` to `cordovaBoolSettingForKey`, it picks up the `<preference name="ScrollEnabled" value="true" />` setting in config.xml.

Can you add this fix to the master please?

**Comment by Mr-Anonymous** [comment]
PR: https://github.com/ionic-team/cordova-plugin-wkwebview-engine/pull/150

**Comment by manucorporat** [comment]
@Mr-Anonymous thanks for the PR! good to close this PR? will tell my coworkers to update the documentation about ScrollEnabled for ionic 1

**Comment by Mr-Anonymous** [comment]
All good. You can close the PR. Updating the doc on ScrollEnabled will be helpful. I noticed the Apache plugin doesnt have that setting.

Thank you so much @manucorporat I was worried if I was gonna be stuck on it and I am glad you took the time to show me the setting. Thanks heaps. I am very happy and excited to release my iOS App with this WKwebview. Much obliged!!

**Comment by Lukargo** [comment]
We're running into this issue as well, and while ScrollEnabled makes it work, it also adds overscroll/bounce to the WebView when there's no content to scroll, which we don't want. Is there a way to disable this without adding no-bounce to every ion-content pane?

**Comment by JulianLaval** [comment]
Experiencing the same! See #153
