### ISSUE TITLE
Can we intercept copy event and change clipboard data?

### ISSUE THREAD

**Issue by Jun711** [ionic-team/cordova-plugin-wkwebview-engine#152]
Just wonder if any of the following 2 features are supported.

1)
https://developer.mozilla.org/en-US/docs/Web/Events/copy
```
document.addEventListener('copy', function(e){
  e.clipboardData.setData('text/plain', 'foo');
  e.preventDefault(); // default behaviour is to copy any selected text
});
```
2)
https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand
document.execCommand('copy')
document.execCommand('cut')

Thank you!

**Comment by manucorporat** [comment]
This plugin does not implement the web engine, it just a cordova plugin that uses the WKWebView provided by Apple. you should check if it is supported by WebKit (safari).
