### ISSUE TITLE
Webserver reachable from the local network

### ISSUE THREAD

**Issue by NiklasMerz** [ionic-team/cordova-plugin-wkwebview-engine#155]
Is the integrated web server properly sandboxed? I am able to connect to the IP of my iPhone on port 8080. This is possible with debug and release build. Even with builds archived and installed through TestFlight. Do I need to check something else?

**Comment by dylanvdmerwe** [comment]
Woah that definitely does not sound right!

**Comment by ghenry22** [comment]
It would actually be a really good option to have, but certainly default to localhost access only for security reasons.

For example casting media to a chromecast from the local webserver allows you to play back media from your phone remotely without an internet connection which is great.

**Comment by NiklasMerz** [comment]
Thats the point. I am concerned about the security too. The code and the log stated the server to be bound on localhost. But the server is accessible from the local network. I just wanted to ask if I am doing something wrong. Is this a bug or is there a parameter to set?

**Comment by timbru31** [comment]
I can confirm that the server can be accessed via the local network.
Can someone from @ionic-team clarify please?

**Comment by manucorporat** [comment]
@timbru31 ok, now it is fixed. Will look at random port selection too
