### ISSUE TITLE
Incompatible with Code Push Plugin

### ISSUE THREAD

**Issue by morganabel** [ionic-team/cordova-plugin-wkwebview-engine#160]
It appears this plugin is incompatible with code push. Both plugins appear to implement `id)loadRequest:(NSURLRequest *)request`

This causes requests to be routed to file:// urls instead of the local webserver.
This explains issue #125 for me

**Comment by cordovapolymer** [comment]
@morganabel do you mean https://github.com/nordnet/cordova-hot-code-push ?

**Comment by morganabel** [comment]
I was using this one: https://github.com/Microsoft/cordova-plugin-code-push but I would imagine the problem might be the same with both plugins

**Comment by richardfan1126** [comment]
Seems you have to modify the `CDVWKWebViewEngine+CodePush.m` file

**Comment by ghaiat** [comment]
hello, does anyone has a solution for this ? we would like to use both plugins (wkwebview+ microsoft code push) ...

**Comment by manucorporat** [comment]
Seems like a bug in: https://github.com/nordnet/cordova-hot-code-push/blob/87f21ab00c8207a668737ae0516aee39ea8ab928/src/ios/WKWebViewFix/CDVWKWebViewEngine%2BHCPPlugin_ReadAccessURL.h

Just do:
```
#define WK_WEBVIEW_ENGINE_IS_USED 0
```
