### ISSUE TITLE
Error in Xcode "_requiresUserActionForMediaPlayback"

### ISSUE THREAD

**Issue by wustenveld** [ionic-team/cordova-plugin-wkwebview-engine#174]
When I want to run the app in a simulator I get an error because of the key "_requiresUserActionForMediaPlayback".

When I open APPBackgroundMode.m and change the key by removing the underscore everything works fine. Maybe this can be default in a next release?

**Comment by mlynch** [comment]
Hi, this looks to be an issue with the `cordova-plugin-background-mode`, correct? Have you filed an issue against that?

If you have any more information on how it's relevant to WKWebView plugin I'd be happy to review that.
