### ISSUE TITLE
Azure Mobile App - App Service's "invokeApi()" call fails when using WKWebView.

### ISSUE THREAD

**Issue by paragw09ckp** [ionic-team/cordova-plugin-wkwebview-engine#175]
I am developing an Ionic App which doesn't perform well (ion-list is broken) with **UIWebView** so trying **WKWebView**. And my Ionic app's server side is deployed in Azure Cloud. The **Azure Mobile App - App Service** is being used as a facade for all the server-side REST calls. 

I have Azure Active Directory for authentication. It appears that the authentication is working fine, I get the access_token back in the app. However, after that when I try to call an Endpoint on my Azure Mobile App using its function "**invokeApi(<REST_URL>)**" I get a connection error. All it says is:

**Unexpected connection failure.**

Any ideas on how to resolve this would be highly appreciated.

Thanks.

**Comment by paragw09ckp** [comment]
Anybody? Hard to believe that I am the first one to try this.

**Comment by mlynch** [comment]
Hmm, seems like an issue somewhere else. It's impossible to debug without more information, unfortunately.

Side note, I'm curious what issues you saw on with ion-list, are those in an issue somewhere?
