### ISSUE TITLE
Scroll starts ~10px off

### ISSUE THREAD

**Issue by mlynch** [ionic-team/cordova-plugin-wkwebview-engine#180]
For some reason content areas start scrolled up about 10px. They "fix" once you scroll, indicating some kind of inconsistent initialization that is fixed by a repaint. Probably a bug in wk but we can probably work around it either in the plugin or in Ionic

**Comment by dalemugford** [comment]
I was able to fix mine by adding `viewport-fit=cover` to index.html meta tag for viewport.

**Comment by dalemugford** [comment]
Wait - it works until I trigger the native library picker for photos— then it's -10px or so from where it should be ;(

**Comment by mlynch** [comment]
Supposedly this fixes it in webkit, so a fix does appear to be coming: https://github.com/WebKit/webkit/commit/cb45630904c7655cc3fb41cbf89db9badd1ef601

We'll want a workaround for now, though

**Comment by mlynch** [comment]
Fixed in 1cb767dbc775ae8ae7dcafa7c27ca2c6b90c21c1

cc @gregavola @dalemugford
