### ISSUE TITLE
config.xml for wkwebview only working for https link not for spec version

### ISSUE THREAD

**Issue by nottinhill** [ionic-team/cordova-plugin-wkwebview-engine#183]
Works:

`    <plugin name="cordova-plugin-wkwebview-engine" spec="https://github.com/ionic-team/cordova-plugin-wkwebview-engine" />`

No Works:

 `   <plugin name="cordova-plugin-wkwebview-engine" spec="1.1.5" />`

How can we force config xml to take 1.1.5 since 1.1.6 breaks everything for us?

 Same for package.json:

No works:

       `"cordova-plugin-wkwebview-engine": "1.1.5",`

Works:

`       "cordova-plugin-wkwebview-engine": "https://github.com/ionic-team/cordova-plugin-wkwebview-engine",`

All 20 other of our plugins flawlessly with "Works"-Method.

This is how we add:

`ionic cordova plugin add cordova-plugin-wkwebview-engine@^1.1.5 --save`

this creates the unwanted git links. Help is appreciated as soon as possible.

**Comment by mlynch** [comment]
Our forked version isn't yet on npm so this is grabbing the Cordova one. We are going to publish under a different name.
