### ISSUE TITLE
White screen when doing some task for long time. [ProcessSuspension] 

### ISSUE THREAD

**Issue by stripathix** [ionic-team/cordova-plugin-wkwebview-engine#185]
This is a really weird bug I am facing in my app where I draw a chart depending on the date selected in the slider.

When this error occurs I see a white screen and the app refreshes.

I see this log in Xcode logs when this white screen shows up:

**2017-09-22 21:43:26.954376+0530 WeatherSpork[1808:504518] [ProcessSuspension] Unable to acquire assertion for process 0**

Looking at the memory and CPU usage I don't see any spikes showing to many memory usages. It remained consistent all the time ranging between 24mb - 26mb. Is 24mb-26mb memory usage too much?

<img width="1062" alt="screen shot 2017-09-22 at 9 43 45 pm" src="https://user-images.githubusercontent.com/8480351/30754339-fc980be2-9fdf-11e7-9b94-580b3b9afb0a.png">

Looks like WkWebview plugin process crashed and restarted and that white screen was the UIWebView process in behind.

Not sure what caused this error:   **[ProcessSuspension] Unable to acquire assertion for process 0**

**Complete Log:**
`[DEBUG] Connection received 580 bytes on socket 22
[DEBUG] Connection on socket 22 preflighting request "GET /var/containers/Bundle/Application/D95C4464-F9F7-4821-B95B-1FCA69549CD1/WeatherSpork.app/www/assets/img/weather/low-ceiling-low-visibility-day.svg" with 580 bytes body
[DEBUG] Connection on socket 22 processing request "GET /var/containers/Bundle/Application/D95C4464-F9F7-4821-B95B-1FCA69549CD1/WeatherSpork.app/www/assets/img/weather/low-ceiling-low-visibility-day.svg" with 580 bytes body
[DEBUG] Connection sent 306 bytes on socket 22
[DEBUG] Connection sent 1553 bytes on socket 22
[DEBUG] Did close connection on socket 22
[VERBOSE] [::1:8080] ::1:64483 200 "GET /var/containers/Bundle/Application/D95C4464-F9F7-4821-B95B-1FCA69549CD1/WeatherSpork.app/www/assets/img/weather/low-ceiling-low-visibility-day.svg" (580 | 1859)
[DEBUG] Did disconnect
[DEBUG] Did end background task
2017-09-22 21:43:26.954376+0530 WeatherSpork[1808:504518] [ProcessSuspension] Unable to acquire assertion for process 0
[DEBUG] Did open connection on socket 17
[DEBUG] Did connect
[DEBUG] Did start background task
[DEBUG] Connection received 448 bytes on socket 17
[DEBUG] Connection on socket 17 preflighting request "GET /var/containers/Bundle/Application/D95C4464-F9F7-4821-B95B-1FCA69549CD1/WeatherSpork.app/www/index.html" with 448 bytes body
[DEBUG] Connection on socket 17 processing request "GET /var/containers/Bundle/Application/D95C4464-F9F7-4821-B95B-1FCA69549CD1/WeatherSpork.app/www/index.html" with 448 bytes body
[DEBUG] Connection sent 303 bytes on socket 17
[DEBUG] Connection sent 10302 bytes on socket 17
[DEBUG] Did close connection on socket 17
[VERBOSE] [::1:8080] ::1:64486 200 "GET /var/containers/Bundle/Application/D95C4464-F9F7-4821-B95B-1FCA69549CD1/WeatherSpork.app/www/index.html" (448 | 10605)
[DEBUG] Did disconnect
[DEBUG] Did end background task`

**Comment by ph0rman** [comment]
I'm also seeing a similar issue that seems to be associated with loading/re-loading WebGL components (nv-d3 charts, CesiumJS maps).  My memory footprint is around 20MB but after a bit it'll white screen with nothing in the console but "[ProcessSuspension] Unable to acquire assertion for process 0".

**Comment by stripathix** [comment]
I have found the culprit in my application. Its canvg library that is used to convert SVG to the canvas, too much memory leaking by setInterval function of canvg. Using this only when really required solved my problem.

Reference to this issue is here: https://github.com/canvg/canvg/issues/405
