### ISSUE TITLE
Doesn't bring up the keyboard when focusing on text elements using RC4

### ISSUE THREAD

**Issue by Tarang** [ionic-team/cordova-plugin-wkwebview-engine#89]
Problem:

focusing on a dom element does not bring the keyboard up with this engine, compared to without it

Expected behaviour

Focusing on an input element should bring the keyboard up.

Ionic Details:

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by ghenry22** [comment]
if I touch an input box the keyboard opens as expected with the latest version of this plugin with RC5.  Not sure if it behaves when the input box is focused programatically though.

**Comment by lpikora** [comment]
same problem on iOS 9.3 simulator. iOS 10 is ok.

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: OS X El Capitan
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by johannds** [comment]
I'm seeing the same thing.

**Comment by onderceylan** [comment]
Until the PR pulled in, you can use https://www.npmjs.com/package/cordova-plugin-wkwebview-inputfocusfix.

**Comment by Fibonacci-Solucoes-Ageis** [comment]
When this will be released?

**Comment by onderceylan** [comment]
@Fibonacci-Solucoes-Ageis it's merged and released.

**Comment by Fibonacci-Solucoes-Ageis** [comment]
On Iphone 8, I focus an input programmatically, the keyboard opens up and after a few miliseconds closes and the input looses focus.
